// GENERATED by scripts/build-exercise-media.mjs — do not hand-edit.
// Frames from free-exercise-db (public domain): https://github.com/yuhonas/free-exercise-db
// 61 stretches · 7 routines · frames live in /exercise-anim.

/** The body areas a training day can leave tight. */
export type MobilityArea =
  | 'hips'
  | 'hamstrings'
  | 'quads'
  | 'calves'
  | 'back'
  | 'chest'
  | 'shoulders'
  | 'neck'
  | 'arms'
  | 'core';

/** Same two-frame contract as ExerciseClip, plus how long to hold it. */
export interface Stretch {
  id: string;
  name: string;
  area: MobilityArea;
  /** Seconds per side. Written by hand — the dataset does not carry one. */
  holdSeconds: number;
  /** One line, readable mid-hold. The dataset's own instructions are far longer. */
  cue: string;
  a: string;
  b: string;
  source: string;
}

export interface MobilityRoutine {
  id: string;
  title: string;
  areas: MobilityArea[];
  /** Holds plus ten seconds between each, to the nearest minute. */
  minutes: number;
  stretchIds: string[];
}

export const STRETCHES: Stretch[] = [
  { id: 'ankle-on-the-knee', name: "Ankle On The Knee", area: 'hips', holdSeconds: 30, cue: "Ankle across the far knee, pull the thigh in until the hip opens.", a: '33932b18c6aafd1c.webp', b: '1f3f4636c1a04f5f.webp', source: "Ankle_On_The_Knee" },
  { id: 'knee-across-the-body', name: "Knee Across The Body", area: 'hips', holdSeconds: 30, cue: "Flat on your back, draw the knee across. Both shoulders stay down.", a: '113462958304bc39.webp', b: '740cc9f51d57ac64.webp', source: "Knee_Across_The_Body" },
  { id: 'lying-glute', name: "Lying Glute", area: 'hips', holdSeconds: 30, cue: "Figure four, hands behind the thigh, pull it toward your chest.", a: '0c237f7cabee5f12.webp', b: 'a72522f55a3013e5.webp', source: "Lying_Glute" },
  { id: 'seated-glute', name: "Seated Glute", area: 'hips', holdSeconds: 30, cue: "Sit tall, ankle on knee, lean forward from the hips not the back.", a: '393a40bcae97ab9d.webp', b: '7369fcc37a7486d3.webp', source: "Seated_Glute" },
  { id: 'lying-bent-leg-groin', name: "Lying Bent Leg Groin", area: 'hips', holdSeconds: 45, cue: "Soles together, knees fall open. Let gravity do it, do not push.", a: '5086309509b75f7b.webp', b: 'ea806bea7a273084.webp', source: "Lying_Bent_Leg_Groin" },
  { id: 'side-lying-groin-stretch', name: "Side Lying Groin Stretch", area: 'hips', holdSeconds: 30, cue: "Bottom leg straight along the floor, ease the inner thigh long.", a: '91a26ee880b382c2.webp', b: '159348de9c1f8b98.webp', source: "Side_Lying_Groin_Stretch" },
  { id: 'kneeling-hip-flexor', name: "Kneeling Hip Flexor", area: 'hips', holdSeconds: 30, cue: "Tuck the tailbone under first, then press the hip forward.", a: '0c7faeddeae4eeed.webp', b: '0d7c139feb344012.webp', source: "Kneeling_Hip_Flexor" },
  { id: 'standing-hip-flexors', name: "Standing Hip Flexors", area: 'hips', holdSeconds: 30, cue: "Square the hips, squeeze the back glute, stand tall.", a: '612198e605cc78ff.webp', b: '95c09c8889ccc303.webp', source: "Standing_Hip_Flexors" },
  { id: 'it-band-and-glute-stretch', name: "IT Band and Glute Stretch", area: 'hips', holdSeconds: 30, cue: "Cross the leg over and lean away until the outer hip pulls.", a: 'f56d199b7017ec71.webp', b: '97009effff3159d0.webp', source: "IT_Band_and_Glute_Stretch" },
  { id: 'worlds-greatest-stretch', name: "World's Greatest Stretch", area: 'hips', holdSeconds: 30, cue: "Deep lunge, elbow inside the foot, then rotate up and open.", a: '95c09c8889ccc303.webp', b: '0e9dc77aff7c5753.webp', source: "Worlds_Greatest_Stretch" },
  { id: '90-90-hamstring', name: "90/90 Hamstring", area: 'hamstrings', holdSeconds: 30, cue: "Hip and knee at ninety, straighten the knee slowly until it bites.", a: '0063f800b8df8995.webp', b: 'b06b98b4d06cd351.webp', source: "90_90_Hamstring" },
  { id: 'lying-hamstring', name: "Lying Hamstring", area: 'hamstrings', holdSeconds: 30, cue: "Leg up, hands behind the thigh. The other leg stays flat.", a: 'd0a0e5477d432e71.webp', b: 'fcc7438f97797deb.webp', source: "Lying_Hamstring" },
  { id: 'seated-hamstring', name: "Seated Hamstring", area: 'hamstrings', holdSeconds: 30, cue: "Hinge from the hips with a long back. Do not round to reach further.", a: '835dd0a8b5354014.webp', b: '5fef87a9d6a5701f.webp', source: "Seated_Hamstring" },
  { id: 'standing-toe-touches', name: "Standing Toe Touches", area: 'hamstrings', holdSeconds: 30, cue: "Soft knees, hang from the hips, let the head go heavy.", a: '88345b5d6826298a.webp', b: '43803784519ba480.webp', source: "Standing_Toe_Touches" },
  { id: 'runners-stretch', name: "Runner's Stretch", area: 'hamstrings', holdSeconds: 30, cue: "Front leg straight, toes up, hinge over it.", a: '912567e46b245502.webp', b: 'ccf95f2cae4620e4.webp', source: "Runners_Stretch" },
  { id: 'leg-up-hamstring-stretch', name: "Leg-Up Hamstring Stretch", area: 'hamstrings', holdSeconds: 30, cue: "Heel on a bench, leg straight, hinge over it with a flat back.", a: '0063f800b8df8995.webp', b: 'b06b98b4d06cd351.webp', source: "Leg-Up_Hamstring_Stretch" },
  { id: 'seated-hamstring-and-calf-stretch', name: "Seated Hamstring and Calf Stretch", area: 'hamstrings', holdSeconds: 30, cue: "Reach for the toes and pull them back toward you.", a: 'de6cfc1c954abfde.webp', b: '6568caa271a5ab10.webp', source: "Seated_Hamstring_and_Calf_Stretch" },
  { id: 'all-fours-quad-stretch', name: "All Fours Quad Stretch", area: 'quads', holdSeconds: 30, cue: "Heel to the backside, knee under the hip, ribs down.", a: '44115d19437805f8.webp', b: '149be0e04b69c8df.webp', source: "All_Fours_Quad_Stretch" },
  { id: 'quad-stretch', name: "Quad Stretch", area: 'quads', holdSeconds: 30, cue: "Knees together, pull the heel in. Hold a wall if you wobble.", a: '04565199f4162be2.webp', b: '8a81c63707186096.webp', source: "Quad_Stretch" },
  { id: 'lying-prone-quadriceps', name: "Lying Prone Quadriceps", area: 'quads', holdSeconds: 30, cue: "Face down, heel to backside. Keep the hip on the floor.", a: 'a534fe01ed84e688.webp', b: '0cd7a62ebf3b363d.webp', source: "Lying_Prone_Quadriceps" },
  { id: 'on-your-side-quad-stretch', name: "On Your Side Quad Stretch", area: 'quads', holdSeconds: 30, cue: "Bottom leg tucked for balance, top heel drawn back.", a: '535e4832d9bee285.webp', b: '2f45f001800a478c.webp', source: "On_Your_Side_Quad_Stretch" },
  { id: 'standing-elevated-quad-stretch', name: "Standing Elevated Quad Stretch", area: 'quads', holdSeconds: 30, cue: "Rear foot on a bench, sink straight down.", a: '69c25e50180d964e.webp', b: '8e65dbe7f28ea6a2.webp', source: "Standing_Elevated_Quad_Stretch" },
  { id: 'calf-stretch-hands-against-wall', name: "Calf Stretch Hands Against Wall", area: 'calves', holdSeconds: 30, cue: "Back leg straight, heel down, hips forward.", a: '62b7c56737a46c83.webp', b: 'b8d2085d3aefdbc2.webp', source: "Calf_Stretch_Hands_Against_Wall" },
  { id: 'standing-gastrocnemius-calf-stretch', name: "Standing Gastrocnemius Calf Stretch", area: 'calves', holdSeconds: 30, cue: "Back knee locked. That is what reaches the upper calf.", a: '427551824bb40f08.webp', b: '30cc88984a1cd4ec.webp', source: "Standing_Gastrocnemius_Calf_Stretch" },
  { id: 'standing-soleus-and-achilles-stretch', name: "Standing Soleus And Achilles Stretch", area: 'calves', holdSeconds: 30, cue: "Same position, back knee bent. Lower calf and Achilles.", a: '612198e605cc78ff.webp', b: '92ab3c5012af0751.webp', source: "Standing_Soleus_And_Achilles_Stretch" },
  { id: 'seated-calf-stretch', name: "Seated Calf Stretch", area: 'calves', holdSeconds: 30, cue: "Towel or band round the ball of the foot, pull it back.", a: '2ae6a03c9227a14d.webp', b: '40ca4eaa99447a0d.webp', source: "Seated_Calf_Stretch" },
  { id: 'ankle-circles', name: "Ankle Circles", area: 'calves', holdSeconds: 20, cue: "Slow and full, both directions. Draw the biggest circle you can.", a: '8c384c3b86b31875.webp', b: 'b13b27f513d304e9.webp', source: "Ankle_Circles" },
  { id: 'childs-pose', name: "Child's Pose", area: 'back', holdSeconds: 45, cue: "Hips to heels, arms long, breathe into the low back.", a: '2408b3b8edd3a404.webp', b: 'f2461c2926cc4cb6.webp', source: "Childs_Pose" },
  { id: 'cat-stretch', name: "Cat Stretch", area: 'back', holdSeconds: 30, cue: "Arch and round one vertebra at a time, with the breath.", a: '44115d19437805f8.webp', b: 'dbd10f97a94d9b7b.webp', source: "Cat_Stretch" },
  { id: 'hug-knees-to-chest', name: "Hug Knees To Chest", area: 'back', holdSeconds: 30, cue: "Both knees in, rock gently side to side.", a: '33932b18c6aafd1c.webp', b: 'f6e48badf499026a.webp', source: "Hug_Knees_To_Chest" },
  { id: 'dancers-stretch', name: "Dancer's Stretch", area: 'back', holdSeconds: 30, cue: "Seated twist. Rotate from the ribs, not the neck.", a: '49b105eca37110ad.webp', b: '5861d3acb446390b.webp', source: "Dancers_Stretch" },
  { id: 'standing-pelvic-tilt', name: "Standing Pelvic Tilt", area: 'back', holdSeconds: 30, cue: "Tuck the tailbone, flatten the low back, hold.", a: '41d75b20702fdea9.webp', b: '329442703f308d50.webp', source: "Standing_Pelvic_Tilt" },
  { id: 'overhead-lat', name: "Overhead Lat", area: 'back', holdSeconds: 30, cue: "Arm overhead, lean away, feel it down the side of the ribs.", a: 'b31a92b2366a1887.webp', b: '4f1312773ca6c435.webp', source: "Overhead_Lat" },
  { id: 'chair-lower-back-stretch', name: "Chair Lower Back Stretch", area: 'back', holdSeconds: 30, cue: "Sit, feet planted, fold forward and let the low back open.", a: '155fa585e512c167.webp', b: '7dc99a178b7c0c5c.webp', source: "Chair_Lower_Back_Stretch" },
  { id: 'side-lying-floor-stretch', name: "Side-Lying Floor Stretch", area: 'back', holdSeconds: 30, cue: "Top arm reaches long, let the shoulder settle.", a: '15c893cf35457624.webp', b: '033d8ee17410b390.webp', source: "Side-Lying_Floor_Stretch" },
  { id: 'middle-back-stretch', name: "Middle Back Stretch", area: 'back', holdSeconds: 30, cue: "Round the upper back and push the hands away.", a: 'b920f25076d700ea.webp', b: '3826e382b73aafb4.webp', source: "Middle_Back_Stretch" },
  { id: 'upper-back-stretch', name: "Upper Back Stretch", area: 'back', holdSeconds: 30, cue: "Clasp the hands, press forward, separate the shoulder blades.", a: '41d75b20702fdea9.webp', b: '3796d7a907b5f900.webp', source: "Upper_Back_Stretch" },
  { id: 'spinal-stretch', name: "Spinal Stretch", area: 'back', holdSeconds: 30, cue: "Long spine, gentle rotation, hold at the first resistance.", a: 'b12c6d4ee3116dfb.webp', b: '04740ec288292115.webp', source: "Spinal_Stretch" },
  { id: 'behind-head-chest-stretch', name: "Behind Head Chest Stretch", area: 'chest', holdSeconds: 30, cue: "Hands behind the head, elbows wide, chest up.", a: 'b09aba5f52ab2ea5.webp', b: '9a98c682ad12eefe.webp', source: "Behind_Head_Chest_Stretch" },
  { id: 'chest-and-front-of-shoulder-stretch', name: "Chest And Front Of Shoulder Stretch", area: 'chest', holdSeconds: 30, cue: "Forearm on the frame, step through, turn away.", a: '2de14127bce0561b.webp', b: '5c8ca45f55861e28.webp', source: "Chest_And_Front_Of_Shoulder_Stretch" },
  { id: 'elbows-back', name: "Elbows Back", area: 'chest', holdSeconds: 30, cue: "Hands clasped behind, lift them and open the collarbones.", a: '88345b5d6826298a.webp', b: '11fc43fc666504bf.webp', source: "Elbows_Back" },
  { id: 'dynamic-chest-stretch', name: "Dynamic Chest Stretch", area: 'chest', holdSeconds: 30, cue: "Swing the arms wide and back. Controlled, not thrown.", a: 'c9e240990bde51e5.webp', b: '977d5a28d9deed5b.webp', source: "Dynamic_Chest_Stretch" },
  { id: 'shoulder-stretch', name: "Shoulder Stretch", area: 'shoulders', holdSeconds: 30, cue: "Arm across the body, pull above the elbow, not on the joint.", a: '43cc9f743cd39445.webp', b: '314b34ecd0088cf3.webp', source: "Shoulder_Stretch" },
  { id: 'seated-front-deltoid', name: "Seated Front Deltoid", area: 'shoulders', holdSeconds: 30, cue: "Hands behind on the floor, slide the hips forward.", a: '5af8f55d63ac5aa6.webp', b: 'a978a9b990aef781.webp', source: "Seated_Front_Deltoid" },
  { id: 'round-the-world-shoulder-stretch', name: "Round The World Shoulder Stretch", area: 'shoulders', holdSeconds: 30, cue: "Big slow arc through the full range. Stop where it pinches.", a: '0d05f2c7643ae20f.webp', b: '7d8f258f6ac4cbcc.webp', source: "Round_The_World_Shoulder_Stretch" },
  { id: 'shoulder-circles', name: "Shoulder Circles", area: 'shoulders', holdSeconds: 30, cue: "Shrug up, roll back, drop. Ten each way.", a: 'd0200cb0e8b0c481.webp', b: '02da863e00fb90a1.webp', source: "Shoulder_Circles" },
  { id: 'arm-circles', name: "Arm Circles", area: 'shoulders', holdSeconds: 30, cue: "Small to large, forward then back.", a: '0a310ad91186ec5a.webp', b: '4d24490b7853f2da.webp', source: "Arm_Circles" },
  { id: 'upward-stretch', name: "Upward Stretch", area: 'shoulders', holdSeconds: 30, cue: "Reach overhead, palms up, lengthen through the ribs.", a: '7669949dd3e3b343.webp', b: '118d498d795a232e.webp', source: "Upward_Stretch" },
  { id: 'chair-upper-body-stretch', name: "Chair Upper Body Stretch", area: 'shoulders', holdSeconds: 30, cue: "Hands on the back of a chair, drop the chest between the arms.", a: 'dcddb95de67378fa.webp', b: '9dc61a373ccec064.webp', source: "Chair_Upper_Body_Stretch" },
  { id: 'chin-to-chest-stretch', name: "Chin To Chest Stretch", area: 'neck', holdSeconds: 30, cue: "Chin down, hands resting on the head. No pulling.", a: '026813fe32433b4d.webp', b: '9bd1a20542516979.webp', source: "Chin_To_Chest_Stretch" },
  { id: 'side-neck-stretch', name: "Side Neck Stretch", area: 'neck', holdSeconds: 30, cue: "Ear to shoulder, opposite shoulder stays down.", a: '1b2c55aaace9a0a0.webp', b: '42aca8b9f95973ce.webp', source: "Side_Neck_Stretch" },
  { id: 'overhead-triceps', name: "Overhead Triceps", area: 'arms', holdSeconds: 30, cue: "Elbow to the ceiling, hand down the spine, ease the elbow back.", a: '20d617b03ea343a5.webp', b: '8216a1d43c0a0cf5.webp', source: "Overhead_Triceps" },
  { id: 'triceps-stretch', name: "Triceps Stretch", area: 'arms', holdSeconds: 30, cue: "Same shape. Ribs stay down, do not arch to get further.", a: '43cc9f743cd39445.webp', b: 'c84ed4ce968956ce.webp', source: "Triceps_Stretch" },
  { id: 'standing-biceps-stretch', name: "Standing Biceps Stretch", area: 'arms', holdSeconds: 30, cue: "Arm back and straight, thumb down, turn away from it.", a: 'edca0701add95de0.webp', b: '1732e439941d1b22.webp', source: "Standing_Biceps_Stretch" },
  { id: 'seated-biceps', name: "Seated Biceps", area: 'arms', holdSeconds: 30, cue: "Hands behind, fingers back, walk the hips forward.", a: 'd2e83600e4e3a8bf.webp', b: '78380c12a0bb4af4.webp', source: "Seated_Biceps" },
  { id: 'kneeling-forearm-stretch', name: "Kneeling Forearm Stretch", area: 'arms', holdSeconds: 30, cue: "Palms down, fingers toward the knees, sit back slowly.", a: 'b3020eaa210e43ba.webp', b: '06c0f5845e079dcb.webp', source: "Kneeling_Forearm_Stretch" },
  { id: 'wrist-circles', name: "Wrist Circles", area: 'arms', holdSeconds: 20, cue: "Both directions, full range. Worth it after a heavy grip day.", a: 'f8794640602ee6d4.webp', b: '579745f3bf7390e7.webp', source: "Wrist_Circles" },
  { id: 'overhead-stretch', name: "Overhead Stretch", area: 'core', holdSeconds: 30, cue: "Reach tall and lengthen from the hip to the fingertips.", a: 'b920f25076d700ea.webp', b: '91379efadf9135c4.webp', source: "Overhead_Stretch" },
  { id: 'standing-lateral-stretch', name: "Standing Lateral Stretch", area: 'core', holdSeconds: 30, cue: "Bend straight sideways. Do not let the hips drift out.", a: 'a845cae69527885e.webp', b: '0936c9801277ba59.webp', source: "Standing_Lateral_Stretch" },
  { id: 'torso-rotation', name: "Torso Rotation", area: 'core', holdSeconds: 30, cue: "Hips face forward, rotate the ribs. Slow both ways.", a: '2d5ef32944ebef74.webp', b: '8f920952846b9d7b.webp', source: "Torso_Rotation" },
  { id: 'lower-back-curl', name: "Lower Back Curl", area: 'core', holdSeconds: 30, cue: "Curl up gently, hold at the top of the breath.", a: '27043f7c81870fb9.webp', b: 'ef0fca1e43fecbb7.webp', source: "Lower_Back_Curl" },
];

export const ROUTINES: MobilityRoutine[] = [
  { id: "post-leg", title: "After a leg day", areas: ['calves', 'hips', 'quads', 'hamstrings', 'back'], minutes: 7, stretchIds: ['standing-gastrocnemius-calf-stretch', 'standing-soleus-and-achilles-stretch', 'standing-hip-flexors', 'quad-stretch', 'runners-stretch', 'lying-hamstring', 'lying-glute', 'lying-bent-leg-groin', 'childs-pose'] },
  { id: "post-push", title: "After chest, shoulders or triceps", areas: ['chest', 'shoulders', 'arms'], minutes: 4, stretchIds: ['elbows-back', 'behind-head-chest-stretch', 'chest-and-front-of-shoulder-stretch', 'shoulder-stretch', 'overhead-triceps', 'seated-front-deltoid'] },
  { id: "post-pull", title: "After back or biceps", areas: ['back', 'arms'], minutes: 4, stretchIds: ['overhead-lat', 'chair-lower-back-stretch', 'upper-back-stretch', 'standing-biceps-stretch', 'kneeling-forearm-stretch', 'childs-pose'] },
  { id: "desk", title: "Desk neck and shoulders", areas: ['neck', 'shoulders', 'chest', 'core'], minutes: 4, stretchIds: ['chin-to-chest-stretch', 'side-neck-stretch', 'shoulder-circles', 'elbows-back', 'chair-upper-body-stretch', 'torso-rotation'] },
  { id: "lower-back", title: "Low back relief", areas: ['back', 'hips', 'hamstrings'], minutes: 5, stretchIds: ['standing-pelvic-tilt', 'cat-stretch', 'hug-knees-to-chest', 'dancers-stretch', 'lying-glute', 'lying-hamstring', 'childs-pose'] },
  { id: "morning", title: "Morning loosen-up", areas: ['shoulders', 'calves', 'back', 'core', 'hamstrings'], minutes: 4, stretchIds: ['arm-circles', 'shoulder-circles', 'ankle-circles', 'cat-stretch', 'standing-lateral-stretch', 'standing-toe-touches'] },
  { id: "full-body", title: "Full body reset", areas: ['shoulders', 'chest', 'arms', 'core', 'back', 'hips', 'quads', 'hamstrings', 'calves'], minutes: 8, stretchIds: ['shoulder-circles', 'behind-head-chest-stretch', 'shoulder-stretch', 'overhead-triceps', 'standing-lateral-stretch', 'overhead-lat', 'standing-hip-flexors', 'quad-stretch', 'standing-toe-touches', 'standing-gastrocnemius-calf-stretch', 'lying-glute', 'childs-pose'] },
];

const BY_ID = new Map(STRETCHES.map((s) => [s.id, s]));

export function stretchById(id: string): Stretch | null {
  return BY_ID.get(id) ?? null;
}

/** The stretches of a routine, in order, skipping any that have gone missing. */
export function routineStretches(routine: MobilityRoutine): Stretch[] {
  return routine.stretchIds.map(stretchById).filter((s): s is Stretch => s !== null);
}

export function stretchesForArea(area: MobilityArea): Stretch[] {
  return STRETCHES.filter((s) => s.area === area);
}
